### DISCUSSION TITLE
Command line, config file documentation/tutorial?

### DISCUSSION THREAD

**Discussion by jatech1** [onthegomap/planetiler#1156] [General]
Is there any place to find documentation or info on the new geojson support and how to add a geojson layer to existing OSM build, or do completely new build with multiple geojson layers only?  Also, any good examples of how to go further and control specific layer settings like min/max zoom levels, included/excluded properties, etc. with teh yaml config file?  Is there a sample yaml file that matches the default full world build of the example command line that could be used as a starting point to add/modify?  Thanks!

**Comment by msbarry** [comment]
You can add a geojson source to a java profile with something like:

```java
Planetiler.create(args)
  setProfile(profile)
  .addGeoJsonSource("mygeojson", Path.of("path", "to", "file.json"))
  .run()
```

Then in your profile's `processFeature` method you'll get source features where source name="mygeojson" and layer="file" (file name without extension) that you can process just like if they had come from any other source like osm.

In yaml, you can add a geojson source:

```yml
sources:
  mygeojson:
    type: geojson
    local_path: "path/to/file.json"
```

then use it in a layer definition:

```yml
layers:
- id: water
  features:
  - source: mygeojson
    geometry: polygon
    include_when:
      natural: water
    attributes:
    - key: natural
    - key: intermittent
```

The default openmaptiles profile is too complex for yaml config so is implemented in Java in https://github.com/openmaptiles/planetiler-openmaptiles. There's not currently a way to combine a java profile and yaml in a single run, so for now you'll need to produce 2 separate mbtiles/pmtiles files.
