### DISCUSSION TITLE
Fragmented line paths at low zoom levels

### DISCUSSION THREAD

**Discussion by zhibek** [onthegomap/planetiler#625] [Q&A] [answered]
Sorry for this basic question - I'm new to vector-based web mapping. If this issue is due to something outside of Planetiler, feel free to tell me!

I'm converting specific OSM ways to line paths in a very simple Planetiler schema - its creating a single layer for "main" railways, setting a minimum zoom level of 4 (see schema below). After generating the mbtiles output, I'm checking it in various tools (`tileserver-gl` example shown below). At low zoom levels, the line paths appear fragmented (i.e. they contain gaps).

Given this issue is displayed regardless of which application I use to view the mbtiles, I don't believe the problem is due to the method of display. I've checked the OSM source and I can't see anything obviously wrong with the ways in the locations where there are gaps. Therefore my basic conclusion is there's either:
(a) An issue with how the mbtiles are being generated (possibly the schema definition I've used needs extra attributes to avoid this problem?).
or;
(b) Fragmented line paths are intrinsic to vector tiles and map styles must be crafted to obscure this problem.

I'd appreciate help in understanding if this issue is related to Planetiler (or the schema I'm using) or if its a more general issue with vector tiles.

For reference, the use-case I'm investigating is generating tiles to be used for displaying railways across large areas (displaying these line strings effectively at zoom levels 6~8 is important for this use-case).

**Example showing fragmented line paths, viewed in tileserver-gl**
![example-fragmented-line-geometry-zoomed-out](https://github.com/onthegomap/planetiler/assets/1309381/7be9c6a8-4622-4bb8-acfd-5097992a354b)

**Example schema**
```
schema_name: Railway Map
schema_description: Railway Map
attribution: <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>
sources:
  osm:
    type: osm
    url: geofabrik:greater-london
layers:
- id: railway_line_main
  features:
  - source: osm
    geometry: line
    min_zoom: 4
    include_when:
      __all__:
      - railway: rail
      - usage: main
    exclude_when:
      service: __any__
```
