### ISSUE TITLE
[BUG] feature removed by `mergeLineStrings()` with "skip clipping" buffer size

### ISSUE THREAD

**Issue by zstadler** [onthegomap/planetiler#1174]
**EDIT:** See [below](https://github.com/onthegomap/planetiler/issues/1174#issuecomment-3018516331) for a reproduction of this issue using a Java profile.

**Describe the bug**

When using `merge_line_strings` with `min_length: 0`, a feature is nevertheless removed from the tiles.

**To Reproduce**

1. Save the following definition in `highway_merge.yml`
```
schema_name: highway_merge (!openmaptiles)
schema_description: Demonstration of merge_line_strings issue
attribution: <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>
args:
  area:
    description: Geofabrik area to download
    default: israel-and-palestine
  osm_url:
    description: OSM URL to download
    default: '${ args.area == "planet" ? "aws:latest" : ("geofabrik:" + args.area) }'
  min_feature_size: 1
  min_feature_size_at_max_zoom: 0

sources:
  osm:
    type: osm
    url: '${ args.osm_url }'

layers:
- id: highway_merge
  tile_post_process:
    merge_line_strings:
      min_length: 0
      tolerance: -1
      buffer: -1
  features:
  - source: osm
    geometry: line
    include_when:
      highway:
    exclude_when:
      - name: ""
    attributes:
    - key: name
```
2. Run Planetiler using Docker
```
docker run --rm -v .:/w -w /w ghcr.io/onthegomap/planetiler highway_merge.yml --output=highway_merge.pmtiles --minzoom=14 --bounds=35.10,31.53,35.10,31.53 --download
```
3. Run tileserver-gl to serve the resulting pmtiles
```
docker run --rm -v .:/data -p 8080:8080 maptiler/tileserver-gl
```
4. Open http://localhost:8080/data/v3/#20/31.523738/35.108367
5. See the gap at the location of the ["Shapira Gate"](https://www.openstreetmap.org/way/462867927) street
![Image](https://github.com/user-attachments/assets/ddb7a3fe-d961-499f-9b10-25effb776239)
7. Kill tileserver-gl using `Ctrl-C`
8. Remove the `tile_post_process` definition from `highway_merge.yml`
9. Repeat steps 2-4
10. The gap is no longer there

![Image](https://github.com/user-attachments/assets/82c1ffdf-bb6b-4bff-b792-500aa65d6099)

**Expected behavior**

The "Shapira Gate" should be preserved when using `merge_line_strings` with `min_length: 0`.

**Environment (please complete the following information):**

- Hardware: Lenovo Legion
- OS: Windows 11 Pro + Docker version 27.4.0, build bde2b89
- Java version and distribution: As used by ghcr.io/onthegomap/planetiler
- Maven version: As used by ghcr.io/onthegomap/planetiler

**Comment by msbarry** [comment]
I think you need to set `min_size: 0` in your feature definition so that all of the line parts get passed along during process so they can be merged in post-process:

```diff
  layers:
  - id: highway_merge
    tile_post_process:
      merge_line_strings:
        min_length: 0
        tolerance: -1
        buffer: -1
    features:
    - source: osm
      geometry: line
+     min_size: 0
      include_when:
        highway:
      exclude_when:
        - name: ""
      attributes:
      - key: name
```

**Comment by zstadler** [comment]
Adding `min_size: 0` doesn't change things. I see the same gap when the post-processing is active. Have you seen a different outcome?

That actually makes sense to me since we're looking at a `max_zoom` tile and `min_feature_size_at_max_zoom=0` is the default.

Actually, I would expect Planetiler to employ an effective `min_size=0` for all LineString features in layers with `merge_line_strings` post-processing. The purpose of the per-feature `min_zoom` is subsumed by the layer's `min_length` settings of the post-processing.

**Comment by zstadler** [comment]
Here is a reproduction of the issue using a Java profile.

This profile creates a `highway_skip_clipping` layer using `-1` buffer to skip clipping
~~~
    return FeatureMerge.mergeLineStrings(items,
      0,	// Do not remove any lines
      -1,	// Skip simplification
      -1 	// Skip clipping
    );
~~~
For our reference, it also creates a `highway_zero_buffer` layer using `0` buffer clipping.

Inspection of the results show that "Shapira Gate" street was removed when clipping was skipped, and kept when a zero-buffer clipping was requested.

To reproduce:
1. Save this code in `highway_merge.java`
    ~~~
    import com.onthegomap.planetiler.FeatureCollector;
    import com.onthegomap.planetiler.FeatureMerge;
    import com.onthegomap.planetiler.Planetiler;
    import com.onthegomap.planetiler.Profile;
    import com.onthegomap.planetiler.VectorTile;
    import com.onthegomap.planetiler.config.Arguments;
    import com.onthegomap.planetiler.config.PlanetilerConfig;
    import com.onthegomap.planetiler.reader.SourceFeature;
    import java.nio.file.Path;
    import java.util.List;

    public class Highways implements Profile {
      private static PlanetilerConfig config;

      private static final String highway_skip_clippingLayerName = "highway_skip_clipping";
      private static final String highway_zero_bufferLayerName = "highway_zero_buffer";

      @Override
      public void processFeature(SourceFeature sourceFeature, FeatureCollector features) {
	if (sourceFeature.canBeLine()) {
	  if (sourceFeature.hasTag("highway") && sourceFeature.hasTag("name:en") ) {
	      features.line(highway_zero_bufferLayerName)
		.setAttr("name", sourceFeature.getString("name:en"))
		.setMinPixelSize(0)
		;
	      features.line(highway_skip_clippingLayerName)
		.setAttr("name", sourceFeature.getString("name:en"))
		.setMinPixelSize(0)
		;
	  }
	}
      }

      @Override
      public List<VectorTile.Feature> postProcessLayerFeatures(String layer, int zoom,
	List<VectorTile.Feature> items) {
	if ("highway_skip_clipping".equals(layer)) {
	  return FeatureMerge.mergeLineStrings(items,
	    0,	// Do not remove any lines
	    -1,	// Skip simplification
	    -1 	// Skip clipping
	  );
	}
	if ("highway_zero_buffer".equals(layer)) {
	  return FeatureMerge.mergeLineStrings(items,
	    0,	// Do not remove any lines
	    -1,	// Skip simplification
	    0 	// Clip to 0 px buffer
	  );
	};
	return items;
      }

      @Override
      public String name() {
	return "Issue 1174 demo";
      }

      @Override
      public String description() {
	return "Demonstration for https://github.com/onthegomap/planetiler/issues/1174";
      }

      @Override
      public String attribution() {
	return """
	  <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>
	  """.trim();
      }

      public static void main(String[] args) throws Exception {
	run(Arguments.fromArgsOrConfigFile(args));
      }

      static void run(Arguments args) throws Exception {
	String area = args.getString("area", "geofabrik area to download", "israel-and-palestine");
	Planetiler planetiler = Planetiler.create(args);
	config = planetiler.config();
	planetiler.setProfile(new Highways())
	  .addOsmSource("osm", Path.of("data", "sources", area + ".osm.pbf"), "geofabrik:" + area)
	  .overwriteOutput(Path.of("data", "highway_merge-java.pmtiles"))
	  .run();
      }
    }
    ~~~
2. Run it with Planetiler or using docker
   ~~~
   docker run --rm -v .:/w --workdir /w --entrypoint java ghcr.io/onthegomap/planetiler -cp @/app/jib-classpath-file highway_merge.java --download
   ~~~
3. Open [PMTiles viewer](https://pmtiles.io/#map=21.19/31.5237197/35.1082458&showTileBoundaries=true&inspectFeatures=true) in a browser.
4. Click "Browse..." and open `data/highway_merge-java.pmtiles`
5. Place the mouse over "Shapira Gate" street to see that it is **not included** in the `highway_skip_clipping` layer:   
   ![Image](https://github.com/user-attachments/assets/987f74d7-35ae-4917-ab37-f3c99cd12d43)
6. Place the mouse over the nearby street to see that it is included in the both layers
   ![Image](https://github.com/user-attachments/assets/37444e71-b980-47ba-ad98-7a1793d63261)

**Comment by natedx** [comment]
Hello, seeing same problem with tile_post_process.merge_line_strings, have you found a fix or workaround @zstadler ?

**Comment by zstadler** [comment]
@natedx,
Unfortunately, no.

**Comment by natedx** [comment]
For those wondering what the cost of removing the post-processing step is, on my particular pbf extract :  
- MBTiles size with post-processing : 2.2GB
- MBTiles size with post-processing removed : 4.8GB

My config for post-processing : 
```
tile_post_process:
    merge_line_strings:
      min_length: 0
      tolerance: -1
      buffer: -1
```

I will come back and add size in the case of `buffer: 0` like you did @zstadler. 

Beyond the doubling of the size of the MBTile database, tiles tend to be huge and complex, particularly at low zooms causing stuttering and bad UX client side. So it **not** a solution to simply remove post-processing.
