### ISSUE TITLE
Expose tile post-processing to schema configs

### ISSUE THREAD

**Issue by msbarry** [onthegomap/planetiler#350]
Needed for shortbread water and street layers

**Comment by msbarry** [comment]
To start with we want to handle anything [FeatureMerge](https://github.com/onthegomap/planetiler/blob/main/planetiler-core/src/main/java/com/onthegomap/planetiler/FeatureMerge.java) can do:

- merge touching linestrings with the same tags
- merge overlapping polygons (optionally with a buffer distance)
- set attributes by sort key

but we also want to leave the API open to support improved functionality in the future outlined in #298 without breaking existing configs

**Comment by wipfli** [comment]
Here is an example for motorways from the shortbread schema which are not connected:

https://wipfli.github.io/swiss-map/#map=5.67/47.53/5.527&inspect

![image](https://user-images.githubusercontent.com/53421382/204124417-0ff85674-5e4f-4c98-864c-afa0e9419199.png)

The relevant section in the `shortbread.yml` file is probably this one:

https://github.com/onthegomap/planetiler/blob/6a893a47870a42d5f916020d126dbe76da849201/planetiler-custommap/src/main/resources/samples/shortbread.yml#L377-L485

**Comment by wipfli** [comment]
Maybe the syntax for merging linestrings in the configurable schema could be something like this:

```yml
##  Streets and Transport 
 - id: streets 
   features: 
   - source: osm 
     geometry: line 
     min_zoom: 
       # ...
     include_when: 
       # ...
     post_process:
       merge_line_strings:
         # options ...
```
