### ISSUE TITLE
[FEATURE] Expose OSM entity metadata in the process feature context

### ISSUE THREAD

**Issue by quincylvania** [onthegomap/planetiler#731]
**Is your feature request related to a problem? Please describe.**
Over at https://github.com/osmus/OpenTrailMap we're using Planetiler tiles as the basis of a QA tool for OpenStreetMap trails. It's great except we'd like to visualize the data based on OSM metadata attributes that don't seem to be available in the Plantiler schema. For example, we might highlight all features older than ten years, or all features created by a specific user.

**Describe the solution you'd like**
The OSM [PBF format](https://wiki.openstreetmap.org/wiki/PBF_Format) supplies the following attributes in the Info field:

```
message Info {
   optional int32 version = 1 [default = -1];
   optional int32 timestamp = 2;
   optional int64 changeset = 3;
   optional int32 uid = 4;
   optional int32 user_sid = 5; // String IDs
   optional bool visible = 6;
}
```

Note that the Info field is technically optional so I suppose some PBF files might not have it.

I propose exposing these variables in the process feature context so that people can use them to include or exclude features, or pass the values through as attributes. Basically I want to be able to do stuff like this in my config file:

```
attributes:
  - key: OSM_VERSION
    value: "${feature.osm_version}"
  - key: OSM_TIMESTAMP
    value: "${feature.osm_timestamp}"
  - key: OSM_TYPE
    value: "${feature.osm_type}"
  - key: OSM_USER
    value: "${feature.osm_user_sid}"
```

**Describe alternatives you've considered**
Just doing this in a dependent project instead of upstream.

**Additional context**
#377 is related but just concerns the feature ID.
