### ISSUE TITLE
[BUG] US admin level 4 boundary lines appear incomplete

### ISSUE THREAD

**Issue by danw-mpl** [onthegomap/planetiler#742]
**Describe the bug**
I can't figure out why US admin level 4 boundary lines appear incomplete?  Is this an issue with Planetiler or the source OSM data?

**To Reproduce**
Use a custom YAML schema.  The problem happens with and without tile post processing, and is consistent with zoom levels.

```yml
schema_name: My Schema
schema_description: v0.1.2
attribution: <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>
sources:
  osm:
    type: osm
    url: '${ args.osm_url }'

layers:
- id: admin_boundaries
  features:
  - source: osm
    geometry: line
    min_size: 0
    min_zoom: 3
    include_when:
      __all__:
      - boundary: administrative
      - admin_level: [ 3, 4 ]
    attributes:
    - key: maritime
      type: boolean
    - key: admin_level
      type: integer
  tile_post_process:
    merge_line_strings:
      min_length: 1
      tolerance: 1
      buffer: 5
```

**Expected behavior**
The admin 4 lines should be complete.

**Screenshots**
<img width="742" alt="Screenshot 2023-12-06 at 12 06 00" src="https://github.com/onthegomap/planetiler/assets/88881405/79e4ee77-1cd0-44ed-8c90-2db5b6f7f280">

**Environment (please complete the following information):**
Docker-based Planetiler (ghcr.io/onthegomap/planetiler:0.7.0)
