### ISSUE TITLE
[FEATURE] Expose OSM feature type

### ISSUE THREAD

**Issue by quincylvania** [onthegomap/planetiler#878]
As a followup to #731, there is still one important OSM metadata value that doesn't seem to be accessible as a variable: the geometry type (`node`, `way`, or `relation`). Basically I want to be able to have attributes like these without forking planetiler: 

```yml
  - key: OSM_TYPE
    value: "${feature.osm_type}" # e.g. `relation`
  - key: OSM_ID
    value: "${feature.osm_type.charAt(0) + feature.id}" # e.g. `r12345678`
```
