### ISSUE TITLE
Unrecognized field `min_tile_cover_size` [BUG] 

### ISSUE THREAD

**Issue by quincylvania** [onthegomap/planetiler#961]
I'm trying to use a custom schema something like this:

```
sources:
  osm:
    type: osm
    local_path: data/sources/planet.osm.pbf
layers:
  - id: trail_poi
    features:
      - source: osm
        geometry: polygon_centroid_if_convex
        min_zoom: 4
        min_tile_cover_size: 0.2
        include_when:
          leisure:
            - park
        attributes:
          - key: leisure
            tag_value: leisure
```

But when I try to use `min_tile_cover_size` I run into this error:

`Exception in thread "main" java.lang.IllegalArgumentException: Unrecognized field "min_tile_cover_size" (class com.onthegomap.planetiler.custommap.configschema.FeatureItem), not marked as ignorable (8 known properties: "min_zoom", "include_when", "geometry", "attributes", "source", "max_zoom", "exclude_when", "min_size"])
`

I guess the value is probably missing from [configschema/FeatureItem.java](https://github.com/onthegomap/planetiler/blob/main/planetiler-custommap/src/main/java/com/onthegomap/planetiler/custommap/configschema/FeatureItem.java)? It's listed in [configschema/AttributeDefinition.java](https://github.com/onthegomap/planetiler/blob/main/planetiler-custommap/src/main/java/com/onthegomap/planetiler/custommap/configschema/AttributeDefinition.java), possibly that's a mistake? Not sure exactly what's going on.
