### ISSUE TITLE
[FEATURE] Add basic geometry attributes for custom schema inline expressions

### ISSUE THREAD

**Issue by quincylvania** [onthegomap/planetiler#979]
**Is your feature request related to a problem? Please describe.**
For OpenTrailMap I'd like to be able to be able to show the trail length. I'd also like to filter parks by size/coverage with MapLibre instead of with `min_size` in the tiles (gets around our need for #965 too).

**Describe the solution you'd like**
I'd like to be able to do something like the below. I'm not sure about the best syntax or property names, or if these should be functions instead.

```
attributes: 
  - key: length
    value: '${ feature.length_km }'
  - key: area
    value: '${ feature.area_km2 }'
  - key: bbox_area
    value: '${ feature.bbox_area_km2 }'
  - key: min_lat
    value: '${ feature.min_lat }'
  - key: min_lon
    value: '${ feature.min_lon }'
  - key: max_lat
    value: '${ feature.max_lat }'
  - key: max_lon
    value: '${ feature.max_lon }'
```

For point features the area/length would return zero and the min/max lat/lon would just be the feature's lat/lon.
